/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * LYPetal Security & Injection Prevention Engine
 * Protects against SQL Injection, NoSQL Injection, Stored Script Injections,
 * Prototype Pollution, and Parameter Tampering across client and server.
 */

// Comprehensive SQL Injection pattern signatures (case-insensitive)
const SQL_INJECTION_PATTERNS = [
  // Tautology / Boolean bypass (e.g., ' or '1'='1, ' or 1=1 --)
  /(\b(?:or|and)\b\s+['"]?[\w]+['"]?\s*=\s*['"]?[\w]+['"]?)/i,
  /(\b(?:or|and)\b\s+\d+\s*=\s*\d+)/i,
  /(\b(?:or|and)\b\s+true\b)/i,
  /('|\")\s*(or|and)\s*('|\")?[\w]+('|\")?\s*=/i,
  
  // Union-based injection (e.g., UNION SELECT, UNION ALL SELECT)
  /(\bunion\b\s+(all\s+)?\bselect\b)/i,
  
  // Data Definition / Destruction (e.g., DROP TABLE, ALTER TABLE, TRUNCATE)
  /(\bdrop\b\s+(table|database|view|column|index)\b)/i,
  /(\balter\b\s+(table|database)\b)/i,
  /(\btruncate\b\s+table\b)/i,

  // Data Manipulation statement injection (e.g., ; DELETE FROM, ; INSERT INTO, ; UPDATE)
  /(;\s*\b(delete\s+from|insert\s+into|update\s+\w+\s+set)\b)/i,
  
  // Database metadata / Schema extraction
  /(\binformation_schema\b|\bsys\.tables\b|\bpg_catalog\b|\bmaster\.\.sysdatabases\b)/i,
  
  // Execution / Stored procedures
  /(\bexec(ute)?\b\s*\(|\bxp_cmdshell\b|\bsp_executesql\b)/i,

  // Time-based blind injection (e.g., WAITFOR DELAY, SLEEP(5), BENCHMARK)
  /(\bwaitfor\b\s+\bdelay\b|\bsleep\s*\(\s*\d+\s*\)|\bbenchmark\s*\(\s*\d+|\bpg_sleep\s*\()/i,

  // SQL Comments used to terminate queries (e.g., --, /* */, #)
  /(--|\/\*[\s\S]*?\*\/)/
];

// Dangerous script tags and JavaScript URI schemes
const SCRIPT_INJECTION_PATTERNS = [
  /<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
  /javascript\s*:/gi,
  /data\s*:\s*text\/html/gi,
  /vbscript\s*:/gi,
  /on\w+\s*=\s*["'][^"']*["']/gi
];

/**
 * Checks if a string contains any SQL Injection signatures.
 */
export function containsSqlInjection(value: string | unknown): boolean {
  if (typeof value !== 'string') return false;
  const normalized = value.trim();
  if (!normalized) return false;

  return SQL_INJECTION_PATTERNS.some((pattern) => pattern.test(normalized));
}

/**
 * Checks if a string contains cross-site script or code injection tags.
 */
export function containsScriptInjection(value: string | unknown): boolean {
  if (typeof value !== 'string') return false;
  const normalized = value.trim();
  if (!normalized) return false;

  return SCRIPT_INJECTION_PATTERNS.some((pattern) => pattern.test(normalized));
}

/**
 * Sanitizes a string by neutralizing SQL meta-characters, SQL comments,
 * and dangerous markup without destroying valid punctuation.
 */
export function sanitizeSqlInput(value: string): string {
  if (typeof value !== 'string') return '';

  let sanitized = value
    // Remove null bytes
    .replace(/\0/g, '')
    // Remove SQL comment lines
    .replace(/--.*$/gm, '')
    // Remove multi-line SQL comment blocks
    .replace(/\/\*[\s\S]*?\*\//g, '')
    // Strip semicolons that could be used for statement stacking
    .replace(/;\s*$/g, '');

  return sanitized.trim();
}

/**
 * General-purpose string sanitizer for user inputs (names, addresses, comments, notes).
 * Strips executable HTML/script tags and controls character lengths.
 */
export function sanitizeText(value: string, maxLength = 1000): string {
  if (typeof value !== 'string') return '';

  let cleaned = value
    .replace(/\0/g, '')
    // Strip HTML tags entirely to prevent XSS
    .replace(/<\/?[^>]+(>|$)/g, '')
    // Normalize whitespace
    .replace(/\s+/g, ' ')
    .trim();

  if (cleaned.length > maxLength) {
    cleaned = cleaned.substring(0, maxLength);
  }

  return cleaned;
}

/**
 * Strictly validates an Order ID.
 * Valid order IDs generated by LYPetal are alphanumeric with hyphens (e.g. ORD-1727161234-A8F2).
 * Rejects any SQL Injection strings, spaces, quotes, or slashes.
 */
export function isValidOrderId(orderId: string): boolean {
  if (!orderId || typeof orderId !== 'string') return false;
  const trimmed = orderId.trim();
  if (trimmed.length < 3 || trimmed.length > 50) return false;
  
  // Strictly allow uppercase letters, lowercase letters, numbers, hyphens, and underscores only
  const validPattern = /^[A-Za-z0-9_-]+$/;
  return validPattern.test(trimmed) && !containsSqlInjection(trimmed);
}

/**
 * Sanitizes search queries entered into the Order Tracker or Inventory Search.
 * Safely strips SQL injection attempts while preserving standard search text.
 */
export function sanitizeSearchQuery(query: string): { 
  cleanQuery: string; 
  hasInjectionRisk: boolean;
} {
  if (!query || typeof query !== 'string') {
    return { cleanQuery: '', hasInjectionRisk: false };
  }

  const raw = query.trim();
  const hasRisk = containsSqlInjection(raw) || containsScriptInjection(raw);

  // If a blatant SQL injection attack is detected (e.g., ' OR '1'='1 or DROP TABLE),
  // return an empty cleanQuery and flag the risk so a friendly security alert is shown.
  if (hasRisk) {
    return { cleanQuery: '', hasInjectionRisk: true };
  }

  // Strip non-alphanumeric punctuation commonly used in SQLi payloads
  const cleaned = raw.replace(/[;'"\\]/g, '').trim();

  return { cleanQuery: cleaned, hasInjectionRisk: false };
}

/**
 * Deeply sanitizes an object or record before writing to Firestore or processing via Express.
 * Neutralizes NoSQL operator injections (like $gt, $ne, $where) and prototype pollution.
 */
export function sanitizePayload<T>(input: T): T {
  if (input === null || input === undefined) {
    return input;
  }

  if (typeof input === 'string') {
    return sanitizeSqlInput(input) as unknown as T;
  }

  if (Array.isArray(input)) {
    return input.map((item) => sanitizePayload(item)) as unknown as T;
  }

  if (typeof input === 'object') {
    const cleanObj: Record<string, any> = {};

    for (const [key, val] of Object.entries(input)) {
      // Prevent prototype pollution
      if (key === '__proto__' || key === 'constructor' || key === 'prototype') {
        continue;
      }
      // Prevent MongoDB / NoSQL operator injection in object keys
      if (key.startsWith('$')) {
        continue;
      }

      cleanObj[key] = sanitizePayload(val);
    }

    return cleanObj as T;
  }

  return input;
}

/**
 * Safely formats any number into localized currency string (e.g. "1,250")
 * Handles undefined, null, NaN, and string numbers gracefully without throwing TypeErrors.
 */
export function formatCurrency(amount: number | string | undefined | null): string {
  if (amount === undefined || amount === null) return '0';
  const num = typeof amount === 'number' ? amount : Number(amount);
  if (isNaN(num)) return '0';
  return num.toLocaleString();
}
